### ISSUE TITLE
Transactions splitting to a value of 127.5

### ISSUE THREAD

**Issue by Myke500** [x42protocol/X42-FullNode-UI#2]
Some users have reported transactions being split and showing in history multiple transactions of 127.5 with the same times stamp on each.  The transactions do not affect the balance.

Unknown steps to reproduce:

Reported on blocks 42163 [user2] & 45382 [user1]

[user1] has reported at the time of occurrence using ver 0.1.7, same history shows in ver 0.1.8
Number of transactions showing *8*
Total value of transactions *1020*
All have the same TXid ```e02c3bbb68c8e102b56be8f31afa1a775888e689d3ced03b9c55f9075d07acd8```

![image](https://user-images.githubusercontent.com/17334141/45655612-08c83780-ba96-11e8-8df6-c4647871b2b1.png)
![image](https://user-images.githubusercontent.com/17334141/45655642-2d241400-ba96-11e8-832c-d4515b779108.png)
![image](https://user-images.githubusercontent.com/17334141/45656043-1d0d3400-ba98-11e8-894b-1449cad9740a.png)

[user2]
Number of transactions showing *8*
Total value of transactions *1020*
![image](https://user-images.githubusercontent.com/17334141/45656051-2a2a2300-ba98-11e8-8bf3-13600e8b2dc4.png)
![image](https://user-images.githubusercontent.com/17334141/45656195-ec79ca00-ba98-11e8-8102-bc5ca90b099c.png)

**Comment by sondreb** [comment]
This is due to UTXO splitting when staking. It will split into 8 different UTXOs, to ensure that your wallet has plenty of UTXO when staking.

**Comment by Myke500** [comment]
I think from a user perspective is that the amounts are displayed in history vs showing +20 stake amount.

**Comment by Myke500** [comment]
This issue does not seem to exist with the most recent upgrades.  It is not showing in the user interfece or not being reported as such.
